### ISSUE TITLE
"The following file already exists" when extracting on windows

### ISSUE THREAD

**Issue by Basilisvirus** [tttapa/docker-arm-cross-toolchain#3]
THe question is: Are the instructions only been tested on linux systems?

I downloaded [armv6-rpi-linux-gnueabihf](https://github.com/tttapa/docker-arm-cross-toolchain/releases/latest/download/x-tools-armv6-rpi-linux-gnueabihf.tar.xz) on windows 11, and trying to inzip it with winrar I get the error that the filt aleady exists. This must be a issue with the unzip process I believe. 

![image](https://github.com/tttapa/docker-arm-cross-toolchain/assets/18421898/f67d106b-63d2-41b0-87dd-07cf673c99bb)

The "double" files it sees are for example in `x-tools\armv6-rpi-linux-gnueabihf\armv6-rpi-linux-gnueabihf\sysroot\usr\include\linux\netfilter ` , the files that are named with Capital and non-capital letters for example `xt_connmark.h` and `xt_CONNMARK.h`

Then I tried using `wget ` on windows but I would rather not do it that way since windows's wget.exe command is not a PowerShell 'wget' command and it usually never works as intended:

```
PS C:\Users\basil\opt> ls
PS C:\Users\basil\opt> wget -O- https://github.com/tttapa/docker-arm-cross-toolchain/releases/latest/download/x-tools-armv6-rpi-linux-gnueabihf.tar.xz | tar xJ -C ~/opt
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'O-'.
At line:1 char:6
+ wget -O- https://github.com/tttapa/docker-arm-cross-toolchain/release ...
+      ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\basil\opt> wget https://github.com/tttapa/docker-arm-cross-toolchain/releases/latest/download/x-tools-armv6-rpi-linux-gnueabihf.tar.xz | tar xJ -C ~/opt
tar.exe: Error opening archive: Failed to open '\\.\tape0'
PS C:\Users\basil\opt>
```

**Comment by Basilisvirus** [comment]
Managed to solve it. 
I can unzip the file if I first make a empty folder and make its contents case sensitive as described here: https://stackoverflow.com/a/60448790/13294095

**Comment by tttapa** [comment]
> Are the instructions only been tested on linux systems?

Indeed, for the simple reason that the cross-compilers run on Linux and target Linux :)

IMHO, it is not worth it to set up a Linux cross-compilation environment on Windows. If for whatever reason you _have_ to use Windows, you're much better off using WSL or Docker.
