### ISSUE TITLE
GCC 14.1 update?

### ISSUE THREAD

**Issue by Zingam** [tttapa/docker-arm-cross-toolchain#6]
Are there plans to update the toolchain to GCC 14.1?
Any tips on a simple update and build?

**Comment by tttapa** [comment]
I'm waiting for [crosstool-ng](https://github.com/crosstool-ng/crosstool-ng) to add GCC 14 support.  
But there are some open pull requests for GCC 14 if you want to try it now, e.g. https://github.com/crosstool-ng/crosstool-ng/pull/2146

**Comment by Zingam** [comment]
Thanks!

**Comment by tttapa** [comment]
Release 0.2.0 now supports GCC 14.
